-- MySQL Script generated by MySQL Workbench
-- Thu Feb 20 09:21:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rxjs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rxjs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rxjs` DEFAULT CHARACTER SET utf8mb3 ;
USE `rxjs` ;

-- -----------------------------------------------------
-- Table `rxjs`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rxjs`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `stationName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rxjs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rxjs`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `gender` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `birthDate` DATE NOT NULL,
  `image` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rxjs`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rxjs`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_device` INT NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `error_code` VARCHAR(100) NULL DEFAULT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_device_idx` (`id_device` ASC) VISIBLE,
  CONSTRAINT `id_device`
    FOREIGN KEY (`id_device`)
    REFERENCES `rxjs`.`device` (`id`),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `rxjs`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rxjs`.`tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rxjs`.`tracker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_device` INT NOT NULL,
  `last_activity` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_service_idx` (`id_device` ASC) VISIBLE,
  CONSTRAINT `id_service`
    FOREIGN KEY (`id_device`)
    REFERENCES `rxjs`.`device` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
